name: 'owas-depcheck-issue-create-action'
description: 'This is a github action that creates an issue based on owas dependency check report.'
inputs:
  repo-token:
    description: 'Token with repo scope'
    required: true
  issue-labels:
    description: 'Comma-separated list of labels for the issue'
    required: false
  minimum-severity:
    description: 'The entries with this severity or above will be shown inside the issue.'
    required: true
  report-file:
    description: The filepath of the json report relative to the project folder.
    required: true
  issue-name:
    description: The Name of the Issue will be merged with the default name "Vulnerability Report <<issue-name>> Found 40"
    required: false
outputs:
  issue-url:
    description: 'URL of the created issue'
runs:
  using: 'node20'
  main: 'index.js'
